apiVersion: v1
kind: Secret
metadata:
    name: wallabag-secret
    namespace: wallabag
type: Opaque
stringData:
    SYMFONY__ENV__SECRET: ENC[AES256_GCM,data:5goXH/cef2OjivUMw8jGhixuNslIruVimq6s1A2m4imDGk3KeCf5YQ==,iv:PhSloyttZWnv87MyWSug1bVsaJFGpPwvPlc3rXeFsFE=,tag:HjbbJVStw9iNVQ7DZWT2EA==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:5H0rtS7Txa64hVFzVLiRoZAxphELnemX,iv:i87PnhPNFjLWWVfj82iZSgE1Zc2QPsP3WpkQB+UhYsE=,tag:6W2Wf7yHzwgD8s7v6MDjOg==,type:str]
sops:
    age:
        - recipient: age1wucu8avdv4q5et0wrpa8pgdg92rrk6dr3j0qg02yrhkratnegpnqf8qc58
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjL29zWkU4cUYyMFcweWJz
            cityczdTNDZaTG9SU2llYWJkdGZTYVo5aGk0CkE5bjhLSjR3S2ZqeTg4bFBNOVJk
            anpjRkdnWmhiOU5mMTJDYTN0dUpDTWcKLS0tIHFhaEJiNkJNemNlZHNXUDJoUkhi
            UVAxYWxqNGJONkg2T0xSYzBZRzBwWGMKWoea32JYj4zqJ9Y8gEeBWAYMHflEl5xZ
            bZ6uC3UktYQZcSDRNMn2lZZKOXKva4VHrN15dzJNJtj3ijAyfQIGbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-24T17:43:49Z"
    mac: ENC[AES256_GCM,data:/wNjgh24NQC53zvYQFcbH2EnLdRfXtZsnUZdd+QIw1c7ZP6IiExcRLWaS9xqN6wN9sITIQ0fRBL2gno46C/FGoxnOWsEToBFnjjCte9NSO9aYccUO/Lz954/BcT4CQPDQUgxXDqcrCVyCvRYUlsuMq0XP3D7KN4+sIKvIuZRtiU=,iv:U6iPCt1cn4TNXeuvGslywqLjdVFf6KLY9YYnXlYMG08=,tag:1Ay7Nrek9XN6COw2EF4iFA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
