apiVersion: v1
kind: PersistentVolume
metadata:
  name: ring-mqtt-pvc-data
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    name: ring-mqtt-pvc-data
    namespace: home-assistant
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  volumeMode: Filesystem
  nfs:
    path: /mnt/md0/k8s/ring-mqtt-data
    server: 192.168.0.76
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ring-mqtt-pvc-data
  namespace: home-assistant
spec:
  volumeName: ring-mqtt-pvc-data
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
