apiVersion: apps/v1
kind: Deployment
metadata:
  name: ring-mqtt
  namespace: home-assistant
  labels:
    app: ring-mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ring-mqtt
  template:
    metadata:
      labels:
        app: ring-mqtt
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
      containers:
      - name: ring-mqtt
        image: tsightler/ring-mqtt
        ports:
        - containerPort: 8554
        volumeMounts:
        - name: ring-mqtt-data
          mountPath: /data
      volumes:
        - name: ring-mqtt-data
          persistentVolumeClaim:
            claimName: ring-mqtt-pvc-data
