apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:9294qRMCmjPNj6b3HZn8rto4BpQLzHeHFRcvVntv+E/omNk9517ueokXtiJVth4tv5w3SFbNQUibaLNN5rtOJAzKaWPj6Jgcy+w2fF01JuCtb+wxoSILke8XbgLi2cdN0+iQM3Z2T1p7k3H3oWfAi7Yees/FZNX06A==,iv:ERs3kYK7sTi1TnoEkXhsE8bJrCjoJdWNX3KTD+Ncf+U=,tag:4iYThgeBpL4JRgOXtmvVAQ==,type:str]
sops:
    age:
        - recipient: age1wucu8avdv4q5et0wrpa8pgdg92rrk6dr3j0qg02yrhkratnegpnqf8qc58
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsM29WcE8vcGFXd3haaEtu
            eEVwN2ZPeFA2dXhLV01WcS84dEx2dzV0SEVBClcycC85K3NZTWdCWFZEWnpxaHBO
            Q0x0TDJpQzlhcmFaVCtQZWNQZm5lQkEKLS0tIFBCQ0htWnVCNGR3ZTFtdFoxRHo2
            L3JKcVU3NHVtRnZWRUhuQWNETGZ6UmMK7hlg6yfTkRHjm9H231LjuywxjtdE9zw2
            /k2dtdSsMppIetFMZxDmgJvkCorJXXnTzqUq63N6xxRtT6SFpXqj8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T16:01:44Z"
    mac: ENC[AES256_GCM,data:Pwqb3mTl/D+N+J+H5NBAmhTSZ5WPCGi+V4WYxDSdMh56p6srcMUOsn1Nj/U7tyQt6obXkpWogCK/lkjSoO4NH8KolZL2kf8lObKC9dAiqUsreH8jjHRphz210eU3HC3QbVG2u/2YtpcZgLrBHt7lbCwtIxgk4QXPqq+CVy/qRjA=,iv:bXmcfB9bZiNl9u7lZ9tExhcaLaGvCFDxhpRhd0aVQP4=,tag:h9j8qQlGC/zWyfnZ4rR4ww==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
