apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: monitoring
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:6u6gbfrXMAkt8tht5TdALSidiJHoB+Np9diOUbGBcFHC3XWw1/nI4L+PoD0sdW8rScUlaPbvYtoASKrR83L4+cJ0e4rTevN9PbNcEn3hyLpu43x6DZr8yDsPUnLNiqj507AYH/zsH2KeMjtnRjh5QeQ8yBnrbcHtwg==,iv:fCoOwxTLGJgvZfcjKGtBuJzntW/99+q9NRT3KvYykAA=,tag:Sz2IQKQGpX64EYIxozp7bQ==,type:str]
sops:
    age:
        - recipient: age1wucu8avdv4q5et0wrpa8pgdg92rrk6dr3j0qg02yrhkratnegpnqf8qc58
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMEpxMEpFcEFrNXRCYVVP
            b0dYVGcwQjY4Zy9XZEsvcnlXS3BzWmowYVJZCnlZRjUvakd5K052SURsNXNGcjVz
            S1VYNDllZGR2YThJMGlKNFVCVjBFbWcKLS0tIG5iUHErQUs1aXRLM1dVK3JMaTZD
            MjJLY0FOUXBmemxDS0hrL1hjZ21rSVEKS1E2w7uRj3fpVnfJfSR57zhL37woeZQS
            /omNG/1CK0PTbvOLKer6NR7Y3eo3mX8Bd2qZhT6fIeke45E1XhsXpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T16:01:44Z"
    mac: ENC[AES256_GCM,data:NNw2rV1jG5qEHs2kbb3TrkjXmDun91u4hC3ux9y1ahw16b/UVU5N3k5x7RB9B46733iMVLzefumWK1dbJnJFd63oQfWblF4t7uQ9nNWBVkxmWCHicvE8yZl6/5SO1Dv78LHfo2JgmjAtGIEuF1uWgmlLcx0lixkL5G9HF40jsas=,iv:81p6n30j5aKmbue8o5hfbvf0KnsHkRj+AI8bzj5EUFI=,tag:N/Xl9aCPk4fODZOxLIAkFw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
