apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 8Gi
  claimRef:
    name: influxdb-data-influxdb-0
    namespace: monitoring
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  volumeMode: Filesystem
  nfs:
    path: /mnt/md0/k8s/influxdb-data
    server: 192.168.0.76
