apiVersion: v1
kind: Secret
metadata:
    name: isfdb-secrets
    namespace: isfdb
type: Opaque
stringData:
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:5sB5Dy6C8mLH54wr1+PBB3lwnGMUf75VIRSJWjmPvzI=,iv:RsDdSkZMSXboEMJzAr0+vllgo8pOTG+sYscBUY4Xj8k=,tag:pxmTTWzFJteUcoVMXgPIHw==,type:str]
    ISFDB_WIKI_USERNAME: ENC[AES256_GCM,data:rxmNeIWEbOQoB4g=,iv:uook8KZrr6eD8ys8Xh8kA+0Jnp70yXElPOCeQA0yILI=,tag:d4TG4Hjogpb5Q3fQKFNVkg==,type:str]
    ISFDB_WIKI_PASSWORD: ENC[AES256_GCM,data:afWVQ6ACZz9Hub39jQTs,iv:OgxR5swIMNEVo8GlVhBRzN/dajqZUOu1pLebtMiLLXw=,tag:M/MbPDvXu3MhOk6iNoZtTA==,type:str]
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:h4fl9A84sJ1NB1MnOUlD0teypJl6JkCeR8yx4gZKpq8Ur6TG2myixfcL5kxddNz5RdsnNzeeKqOy1i4M9PuttoeH0x8D8E5G,iv:mydGx4GtoeMt7RI8q2plTdj8bkHDhHbz79jGZNKeB/U=,tag:kGZ2QFqCzHy9KF/rGb2Osg==,type:str]
    DISCORD_CHANNEL_ID: ENC[AES256_GCM,data:HCjqwZLFAzupbEwqQ2z0gzQk+Q==,iv:E4mjdGBALltP1o0LZYRcA+OUj61fgJnpFJ/56z8/O7k=,tag:byw0RepXm/cgCL9hYVCRXQ==,type:str]
sops:
    age:
        - recipient: age1wucu8avdv4q5et0wrpa8pgdg92rrk6dr3j0qg02yrhkratnegpnqf8qc58
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1bUtKdi96UnhIUlZwbDIz
            QWgwUzM2UWdQRmM1bFd6TlUyRGNIdHdsTmg4CkorZlYwMEZMejl6a3dZSTBZVjNa
            ZE1XZi9vTmozQlQrS2hQcHlNeFJtZGcKLS0tIGxabCtuV0RQUmdCeVRTay9SWEdI
            R0o1c3lBUk9zcGhMMXlTblR2VmJCRUkKKCY2ifybQA8SwXmmH2J8Mr/qE77rYr8c
            TihipIbJC56XP5/X+qeALzLsw9cIEHqDVaiboWRft/psfpfGaNCe7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-19T11:35:39Z"
    mac: ENC[AES256_GCM,data:I/SkE+dvedjTY0r3UsOp16VUD53smVhfO76CqsUJcNedG+tujxvqdzt/1X+hfUI6dn18MK1eSYP4Vra2yHlCp3xnFBD52A0BDj94r44uA3oSi7pAUL0/nlXs0l6DGxUi1lwoOXaFoSbH6laU7SMsp/RwYnBKmg3IRGJtj3GZeww=,iv:XReY7tlNphC6yJ/pmQLninfiuLcOfWoOEaHT+fAfFew=,tag:MRqmolqlHBtvIFZtTpXL7w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
