apiVersion: v1
kind: Secret
metadata:
    name: isfdb-secrets
    namespace: isfdb
type: Opaque
stringData:
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:N1EPnkcjjKfaW5WG+HlNWCwfcwCoE3biq050YkBeSug=,iv:RofkOqBdZ6Hn5hjAy6XN/uhWCtEaJZmWYnMHkvBQC3Q=,tag:/om0nIibBTyLWFGbKOWJVw==,type:str]
    ISFDB_WIKI_USERNAME: ENC[AES256_GCM,data:CoUUq14WAAvkNmY=,iv:HmHFP6UbOy461b58gBVg75ZIVSOFn1fYNlDvDYRWx80=,tag:J/VI+kpGa13dme9lTB9ngg==,type:str]
    ISFDB_WIKI_PASSWORD: ENC[AES256_GCM,data:8iEWcKkkBY6nBkHn00CJ,iv:HOrOrWfKxL00um7wXUuq2Cln2JJcgC+hrqyvHQA0mfg=,tag:X8RWr27JX40+O2alWdKRzQ==,type:str]
sops:
    age:
        - recipient: age1wucu8avdv4q5et0wrpa8pgdg92rrk6dr3j0qg02yrhkratnegpnqf8qc58
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdTVWeXNqeDRDSmhUOFR4
            NHl3ZGtTUlNmRTRiQktwWWhXSXRyVnl2L0FJCkVHMkxDNW9LbnZRbVpOSDMxem02
            S0htV3J2Z0lJVUZhYkFMYkpIaHV4dlUKLS0tIHFKeGZhNlRrVUlidm9lTWxLVi9s
            QmpseCtTYy80bC9IcDVZWjNYZDZGZTQKlFvRjBjV0aJ2y87o+kcsA+2LnRtUUGzh
            A0/cRl9IUk42DX4stPwooGOAD1QTEnhileIl+L5hbzViSGFBcTFUHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-25T13:26:48Z"
    mac: ENC[AES256_GCM,data:d0zKFjfivgle8CZ72Xnq/Oh+DYGSnhnDxB5MG10uqmfyafHRoaVgekvHj9djG1tqnvW/z2eM0W6vciyHVBkLwg4YJHItrJdhoBfV8m7NRAnT97nK7/DwyYo/ULU1pIkqJGLaHOfkhY4PG0RsXduU7w2eN+fMwX2H0wier5Z4FxE=,iv:F++WNBbcxSe3iP8j4FWfN2CTGZ1DG8iW9+0uoFNGuZw=,tag:6dyFGOuBQ0DaU75kQU/7Xg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
