apiVersion: v1
kind: Secret
metadata:
    name: isfdb-secrets
    namespace: isfdb
type: Opaque
stringData:
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:w2/vRNhxQbIlQs2RPb44mMTy63JgxqOXpHn1GWtWAvw=,iv:QxB+wRXDX6Bv85SReatSViBTDDUtagcBHoMz2XsIscs=,tag:2o04aJYlp3j7hxNFr1JzdA==,type:str]
    ISFDB_WIKI_USERNAME: ENC[AES256_GCM,data:9oHHlGMpKq9GXBM=,iv:kkOnpdYZwY0ycPGqxA/OZgf2hFF9BYL9MwZCohzwX10=,tag:wwQo74pOt5KiIk/1TGBV/A==,type:str]
    ISFDB_WIKI_PASSWORD: ENC[AES256_GCM,data:17TcBc68ECx4xfYgzdk+,iv:lUXxtWxpkAijBGcn5AJKiqf1WnqrR8MHSPEUR75SHPk=,tag:jkI1XqVek+454Y2jrmoayA==,type:str]
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:ChZ91eRG2IANsAGjnuTd8VtqhkVu+dmt+a6CnND5SbGX2Hiq8bz/9uejbd8JEiyLzuQ+WiTH+axatBrvKCca5gfi2zi4cUk8,iv:F+q4mqzGLjDLxjRv4BlKz65k/8+9a9PETOXf0Qtfw9Y=,tag:rp2I2F5FOeBBiTfHSOePeA==,type:str]
    DISCORD_CHANNEL_ID: ENC[AES256_GCM,data:iWjT//B55d34b1Y/8PMP4JgbPg==,iv:sjsB392MKYDahkRgikiKLV+bPPaeI26NvyGfXZjyBS0=,tag:ZIVUo3Ai4/+O1SI1b8K0Uw==,type:int]
sops:
    age:
        - recipient: age1wucu8avdv4q5et0wrpa8pgdg92rrk6dr3j0qg02yrhkratnegpnqf8qc58
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSHBYNW5ZYVVFSldoOFI4
            ZTJ0bi83MzZad0xKQmZrWHNaZGdFU3pBMjFvCnc4eUlPWnlEWklrQXYvMHZuYkd2
            Nmc0QVdjUk94bGdDNEVIVHNJRUxDemMKLS0tIDRhUkwyWHZ2d3d4WDR3cXc2QnNJ
            TzBwZ2RmaXR2QVc0Q3lpUFlRendVVmcKadYdDGakQXsjFbqpTkx+Wn2sphGyDvtD
            4ezEe3Bc8J7w1oks/AX1F0J6XNCETc9lhYiGb8IlANgdc3k/13F0cQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-19T11:33:49Z"
    mac: ENC[AES256_GCM,data:ZwxQ6TFVkIy9phyaavm9oCoaJ3RC/GgUGXtOQiDSRPDgTUr9hVt7tAWqO36seLAjxxMwQEB4+ftoOUxLtjL3hrKvStUAZDCnUHv1iOgxdHnPOWm/n3tiPWm1lchbWkDAMxbEHuPYaPdT8EJ1IeCcs1ymeRNQOOvjTYAOuXlvqgg=,iv:Czsg/JpIqh8N8G5aB37G36s/6Fd6yg4XVyWa0IryJy0=,tag:UzFlVgX7LKMZ1F3WL8GSyQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
