apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - isfdb-secret.yaml
  - mariadb-statefulset.yaml
  - adapter-deployment.yaml
  - ingress.yaml
  - refresh-cronjob.yaml
