{
 "title": "Observatory",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Radar",
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 2, "y": 0 },
   "options": {
    "content": "<center>\n<iframe width=\"250\" height=\"200\" src=\"https://embed.windy.com/embed2.html?lat=52.196&lon=0.121&detailLat=52.137&detailLon=0.212&width=250&height=200&zoom=9&level=surface&overlay=radar&product=radar&menu=&message=&marker=&calendar=now&pressure=&type=map&location=coordinates&detail=&metricWind=km%2Fh&metricTemp=%C2%B0C&radarRange=-1\" frameborder=\"0\"></iframe>\n</center>"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Allsky",
   "type": "text",
   "gridPos": { "h": 13, "w": 10, "x": 6, "y": 0 },
   "options": {
    "content": "<center>\n    <iframe width=\"600\" height=\"500\" src=\"http://k8s.ecafe.org/zephyr/\" frameborder=0></iframe>\n</center>"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "cloudCoverPercent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outside temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "outTemp_C" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dew point",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "dewpoint_C" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rain",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "cm" } },
   "yaxes": [
    { "format": "cm" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "rain_cm" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind",
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 2, "y": 7 },
   "options": {
    "content": "<center>\n<iframe width=\"250\" height=\"200\" src=\"https://embed.windy.com/embed2.html?lat=52.196&lon=0.121&detailLat=52.137&detailLon=0.212&width=250&height=200&zoom=9&level=surface&overlay=wind&product=ecmwf&menu=&message=&marker=&calendar=now&pressure=&type=map&location=coordinates&detail=&metricWind=km%2Fh&metricTemp=%C2%B0C&radarRange=-1\" frameborder=\"0\"></iframe>\n</center>"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sky quality",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "illuminance_sky_quality" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Forecast",
   "type": "text",
   "gridPos": { "h": 7, "w": 10, "x": 6, "y": 13 },
   "options": {
    "content": "<center><a href=\"https://clearoutside.com/forecast/52.21/0.12\"><img src=\"https://clearoutside.com/forecast_image_medium/52.21/0.12/forecast.png\" /></a></center>"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind gust",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT max(\"windSpeed_kph\") FROM \"autogen\".\"mqtt_consumer\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "windSpeed_kph" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Planisphere",
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 19, "y": 13 },
   "options": {
    "content": "<script language='javascript'>\n function imageRefresh(img, timeout) {\n    setTimeout(function() {\n     var d = new Date;\n     var http = img.src;\n     if (http.indexOf(\"&d=\") != -1) { http = http.split(\"&d=\")[0]; } \n\n     img.src = http + '&d=' + d.getTime();\n    }, timeout);\n  }\n</script>\n<center><img src=\"https://www.heavens-above.com/wholeskychart.ashx?lat=52.21&lng=0.12&loc=Cambridge&alt=0&tz=GMT&size=400&SL=1&SN=0&BW=0&ecl=1&cb=0\"  onload='imageRefresh(this, 3600000);'></center>"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Visibility",
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 2, "y": 14 },
   "options": {
    "content": "<center>\n<iframe width=\"250\" height=\"200\" src=\"https://embed.windy.com/embed2.html?lat=52.196&lon=0.121&detailLat=52.137&detailLon=0.212&width=250&height=200&zoom=9&level=surface&overlay=visibility&product=ecmwf&menu=&message=&marker=&calendar=now&pressure=&type=map&location=coordinates&detail=&metricWind=km%2Fh&metricTemp=%C2%B0C&radarRange=-1\" frameborder=\"0\"></iframe>\n</center>"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Todays rain",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "cm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT \"cloudCoverPercent\" FROM \"autogen\".\"mqtt_consumer\" WHERE $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "dayRain_cm" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cloudbase",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT \"cloudCoverPercent\" FROM \"autogen\".\"mqtt_consumer\" WHERE $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "cloudbase_meter" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cloud cover",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 19, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "cloudCoverPercent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}