apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:JdfqyQE=,iv:Gsv/DsKO+2cTCMBLVx0bmgULaSMTWBREgfCtMgM4lKA=,tag:HdXLc0Mjeo9gsPt5Z10MWQ==,type:str]
    admin-password: ENC[AES256_GCM,data:1jgmXX+3FV+gWM/OD3PC3UcmcnRl1zOAVlnB3Q==,iv:73CgEocmLeVanisKXVRQrqfzGlDEFKl1h8HOErR9qsU=,tag:dEkLKhUtQr6jxKrFryqXMQ==,type:str]
sops:
    age:
        - recipient: age1wucu8avdv4q5et0wrpa8pgdg92rrk6dr3j0qg02yrhkratnegpnqf8qc58
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VC9hbTUwL2QyY1NKVkR4
            K3VBWUtMQlNLejB3NXhyVUhBQ3JNWlpJUTJRClFTYlI4dHNpcnlWcjVHNTJjK2JC
            emNsRWRsQUlxNk11c2EyMmRzVmQxMDAKLS0tIEZSczZlemF5eEdBQmROejMxTE9n
            TkdRWTlJZmN5blpNWU0rUytGSDZZaW8KSThNslJDouoW3OzgzuaM0TTmnbJHiGyI
            8BrY/c6yO4UK5xM2eVTKIDe7giRLYhkfq4ggY3KkrI+DTyEedMvDcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T17:08:06Z"
    mac: ENC[AES256_GCM,data:8Wqz+cNcltOnkQW09E52BpzTmMG9Pb/mtC7gIuFW7jGA+VquEHq13qEs2mT75Gh96vqKUG8GnbZU2G1mmiNy/7cjwHf6rFgX3SZUqj3qxzFb/RnbYRxU+YPOXfSrHOz2jYqbKBT/4Eo9hnen0eSH7LC0wYFu7biTE6d2AQGndF4=,iv:Ah1tvfhnO7Z+vigNk9JqZTOSnPf7i6qd8H05Esy1inA=,tag:xHRBWqxDKh1j06RrBhLdDQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
