apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    name: grafana-data-pvc
    namespace: monitoring
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  volumeMode: Filesystem
  nfs:
    path: /mnt/md0/k8s/grafana-data
    server: 192.168.0.76
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-data-pvc
spec:
  storageClassName: nfs-client
  volumeName: grafana-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
