apiVersion: v1
kind: Secret
metadata:
    name: botkube-discord
    namespace: botkube
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:6pMwG2p7bDh6Ewp1yQZK0ngrTLcecP1b28SBtKLOBMLb7h84wiIUemNaBB2vruN0Da/6qSdiFlL52AFJgyfak0RXMj9aRIKoEGDPa8CavUXFI9i/oiFp7xcgU11d7qNmxInGQNUKDcT2JaLWiu+nJvA406+O++8ZgC31WnFT7TNHuQJvXttUWq/tHXu/HOrJlt78bdN1okEvG0bYlU5QOrwKwtU5CM8Xy7BfSl5go5YTe9IE/PRoaK4c1qemvwmziMeIlkGtNnZ5tBdj+UBhay5yha3uTGEPSAxwMPHTIgLJpUI3A4F/YxqNGD1yF9oM5VP5TvFKOnYZif/91f7iWc4eiNs9bzLF8Vkpni2/4gVHRx2vYg==,iv:bd1wT1LjYbfNFfw2/souEN7duBSrnFS+dy4jKHlsiIg=,tag:2utCh3o6G4QqSh174eTEIQ==,type:str]
sops:
    age:
        - recipient: age1wucu8avdv4q5et0wrpa8pgdg92rrk6dr3j0qg02yrhkratnegpnqf8qc58
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVlFEU1ZjQnBodnJBdVdC
            N2cxZlN2RUF5SDE4anZpd0FwY1VjOWRwdG1vClU1VlN1dFhRVHZFc2dmakNwMCtw
            YkFsSEp3T1BpNWdSblEwYXU4WHN2MTQKLS0tIHQwNXVsN210N0JMeVZMQ3B6WU5m
            MzgweDg4QWdlTSs5MXdjczQ0MFdiUG8KnDs97rJJBW3nGvqLAi06dtdWaCHiuBvB
            i7Y5Op7YXEcpA7da3DQkvVVDCENYd+DYQo4IIpzDR4Bn3VUHbTpGFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T18:03:55Z"
    mac: ENC[AES256_GCM,data:i82fuGQdq2w+Hz/q88ffj8V17dPX2Y2fXBq4K+Ht1ZFKB3MJYonQLG+H++lamIASkPgTSP5BjRlKshnNAW9fgAGFIvRi6fcuTppnppKk+F9I53MuqPwLkfaqiXyuszuSx1ms4yp6j/pujz5s6AsddSluDqoQ/nA7CxatSXkEZAc=,iv:UGTvHWhm54YJJOihrtarUctWYnhwduQddqpB7aCxO0Y=,tag:8gGI9osb1koZsNfL0Gac9Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
