apiVersion: v1
kind: Secret
metadata:
    name: botkube-discord
    namespace: botkube
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:a2MCtkwm5+kADVDz4a6+v6Pwt6zpbHLThsd9sU7uGXtNXBaVzqA64MVt2HG2R8r7r2tpMYIkUYRq0xwfRyWQVLdOMG/FPCldmewjG9ocgYoVGvjruoe2WGh/sXkd8ESZ/sRu1MFlouqak5raNIwemK6wUGBhMNIAhWbpLpQkpUEzZQk0yJ6lQ5RxtIc+ScSkc1RvFNVkuPJ0b0c8qCsEBXt5gQvgvAAiAwiJi7u3uRlzzp/Ujn3qvUfZPfOlqVsnN1SyLPiCf5jbQ3gqwBJghhZyfo2lCu6ESkT/Bisf9wLSZpyIM8Px+4rIYVN4UyH7KJc=,iv:wRyUnhKYM7z2/EX7UaOvtLsA/yhaVU1t7ZgZnesFN98=,tag:06iYznYN3iJ/4cqUyMncFQ==,type:str]
sops:
    age:
        - recipient: age1wucu8avdv4q5et0wrpa8pgdg92rrk6dr3j0qg02yrhkratnegpnqf8qc58
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBON0FxSElpcjJ6UVUvZy9k
            bC8rMmREOGh0cEhGREJtaGdEN3NIeENBNmk0CkUzYS9IVlY1emxLRFUxbHR4bXJn
            d2lIMklrMWxvU1JzQkJuSUpDMkRYNmcKLS0tIDF3a2Fid0M0c0Y2SnhnMHQ1VHUy
            bXk0Vkdhb3Arb3BUNExwdE1yVVNNbzAKwNxW72Mm0ziV+Hjd4GDaChvplLw8hqE8
            HD78neJxEB4hXIJK5Q9dWbxAJ5JQhztO0XlN3p1FEmFIa8k55t7J7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T16:58:17Z"
    mac: ENC[AES256_GCM,data:Dh/7Soh6UH6KKcpPwxruy2RjSwRkTS1FfmhST2fQ/mZfqAIuDcv5Ib5Y203UWZbU7dvbx+1NeG9KGUuPnXBeRKMbuUh6Y5lHwsHa5SjDKT0wck8+DBf3aQfbTaV4i+KwOD5emDA9yJChfbsKi1bF+dhxWh+kL3VF6Fbc55+6v00=,iv:LezRBrPQCtDQwEPwK6vvkeIsWIUY3ZqPWOpd/YLlXNo=,tag:2EurDS8Ml3JR73i1aPyoZw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
