apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant-ingress
  namespace: home-assistant # <--- This is your Home Assistant namespace
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: home-assistant.k8s.ecafe.org
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: homeassistant-service
            port:
              number: 8123
  - host: epigone.ecafe.org
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: homeassistant-service
            port:
              number: 8123
  tls:
  - hosts:
    - epigone.ecafe.org
    secretName: epigone.ecafe.org-production
