apiVersion: v1
kind: PersistentVolume
metadata:
  name: homeassistant-pv-config
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    name: homeassistant-pvc-config
    namespace: home-assistant
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  volumeMode: Filesystem
  nfs:
    path: /mnt/md0/k8s/homeassistant-config
    server: 192.168.0.76
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-pvc-config
  namespace: home-assistant
  labels:
    app: homeassistant-label
spec:
  volumeName: homeassistant-pv-config
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
