apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: librarium-covers
  namespace: librarium
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: librarium-media
  namespace: librarium
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
