apiVersion: v1
kind: Secret
metadata:
    name: librarium-secrets
    namespace: librarium
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:vE6J9iKV3QKiBUpQnhDp9zq0ztG/rfxgteloM0WXWILpYlyUeiRuSoD1DmAtz2j8h9TGht9vQTLEcump9VKMmA==,iv:fS0b4X9y4E0mEKR0ilWnM2ylkT31wPqggc/1XQwlEjE=,tag:PV6PhjPOxmxyUzqr6d+8rw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:GNG4ufznZ3M46vj6nr42iZOmrKzi08yLzZ47SU4DrTw4cHbg6xVf56ly2spP4tUWotA1Kn8m2tLkb9gKzQAwIiNCejN0Uqt0welJ+ERET9uvyKfs2UIscl7ViH7gv2D0mw==,iv:dmEf+UyQ+HpmLGKL9QbwzvzwXo+QLG0p5ssLLB1/Vuk=,tag:afxtvlfENjbpzeHJCV1pWw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:wHhGXPBIj2ySYfHIkOM0cv5a7FGhqi1O0Cgglmt3bS8=,iv:B1zgaNcCpKYLg53YBiiH6KG5fItNVdm3+/YP7xM2FEc=,tag:tfE2uz1g6BV4+MijLHObEw==,type:str]
sops:
    age:
        - recipient: age1wucu8avdv4q5et0wrpa8pgdg92rrk6dr3j0qg02yrhkratnegpnqf8qc58
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NDFaY3lhOEF4Z0VXRDlv
            VlFxSUZhVjlIaWZGRTArL1cwQWhsRUFwcDJ3CnR5aU1CRXR4dnY3UnFwdHJhUURS
            eUIvemtXcU9lbFlLb2grZUUzV3hlam8KLS0tIFQ2TDBqUmtHdnlqSzRSNHNwMFc3
            S214TUh0VnlTVlR6S2x5Nk4zbWR2S1EKs0yKo78+kYNLvbn8DwNoNC/lwD2b/iYW
            7OEzSlUdIxo8a8HsOqLdHYt5wJagmu2+AypHBuO2ZwOsg3bGo8M92A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-25T11:04:50Z"
    mac: ENC[AES256_GCM,data:kQtXpT/OfNqDRBYR36yjFPKb99g096nF7DbWk8eSwdrjL8vl2jqFd2bekzTQU1lVarvMqpUJO+l28GjGUzB4zCsAkWZOOEgff4P7ZzatVFdS4bBFgm+Il42Kl3F31uKJNwjqcrBnH3a+DulH3l15s9cW4ofIlpF2jSke0tk25uU=,iv:OUaO89YsqBQXAeumjGxC3og9z9k8THtMZgDIOWDZEiY=,tag://H28VayVXWllhHPG2Xpew==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
