apiVersion: v1
kind: PersistentVolume
metadata:
  name: webdav-data-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  claimRef:
    name: webdav-data-pvc
    namespace: default
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  volumeMode: Filesystem
  nfs:
    path: /mnt/md0/k8s/webdav-data
    server: 192.168.0.76
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webdav-data-pvc
  namespace: default
spec:
  volumeName: webdav-data-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 20Gi
