apiVersion: v1
kind: Secret
metadata:
    name: webdav-config
    namespace: default
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:iZmd79ccTTMbQ9+TNoObSdaP0bDEvsMzluxisv0fYnXB2pm/aeypoDDJEKcACh7ahuvAnRdub2B5s71XU3hr2+py1ZW0NSHa++fRlJYJueFd86mqMm1E61fo19De7MmhezLBiO927WvEKmeDPY6A34x2ExTZoD865ijNEXDcG6t6EAff7HmtVkX/i4ambfO8aiaYPKoI7yYn8uQ20K8SXFgZr1QXrFJ4KFRgbpe1hQ8HuoGWtMpAq4c8rowHXCRyYNkybg==,iv:7U0+27aGKmaYL7c3r2kEwP5lJFgWNu00ob+kUCWaIQ4=,tag:Syn0/xOdEE4xfn7e5hmROQ==,type:str]
sops:
    age:
        - recipient: age1wucu8avdv4q5et0wrpa8pgdg92rrk6dr3j0qg02yrhkratnegpnqf8qc58
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQTgvOGdCVUpYK1RFNGRR
            dWlRb2JvRHh0Q2xwMm90Y3JSWFJtaUFUcmxrCkJPZGI0cUFFbldnVnZJLy9rOGh4
            djRidCtRQ3RiT0s2Tk1IblBSRzNxTXMKLS0tIG94eTRmMHF5cVptREN3MW1lOVJS
            My82VHBUYlFzNEhrSm50RGpQeWRNKzAK7xIXVEPGtKiPFInhy1bK1A5P6xgj4eNB
            lS88o3zMx6EQ5xpxcFQRGETDabADUyBbkcvhzjkrSemWOeg9gBBUdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-15T13:02:44Z"
    mac: ENC[AES256_GCM,data:P6lKKkV3tmBXUuvXvQ1w7UN1tt4j9GhwtqBUzQCtEp93dhrsCgPnnzoP0gWYHYlVdFBo5RNM6FnrBkZVkXQxgqXei/qsVq8rlcbpy7Amq0CeLuhgdXsRmrPzYoGihIjPr81vBjDnl6QfFYYzkCdwvoO9/WVOSD//fqOgddbMPqk=,iv:KEJwzR2J+ZitGsjVJszb2ORpoPjvqQCvDRMN3OidAcI=,tag:U6HYTdET1MDFNqJdHj3tAA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
