apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
  namespace: linkding
  labels:
    app: linkding
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
      containers:
        - name: linkding
          image: sissbruecker/linkding:1.45.0
          ports:
            - name: linkding
              containerPort: 9090
          env:
            - name: LD_CSRF_TRUSTED_ORIGINS
              value: http://pinboard.k8s.ecafe.org
            - name: LD_SUPERUSER_NAME
              valueFrom:
                secretKeyRef:
                  name: linkding-secret
                  key: LD_SUPERUSER_NAME
            - name: LD_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: linkding-secret
                  key: LD_SUPERUSER_PASSWORD
            - name: LD_SUPERUSER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: linkding-secret
                  key: LD_SUPERUSER_EMAIL
          volumeMounts:
            - name: data
              mountPath: /etc/linkding/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: linkding-data-pvc
