apiVersion: v1
kind: Secret
metadata:
    name: linkding-api-token
    namespace: linkding
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:YXTBPVrpA51uIrDBGFdPlQ4ZRT1AT/+1Edy0yh/x0XUM14cjJUrtgg==,iv:lhtjFslZRDcP/pny8x2jBqYhs1i8no9J1yJfNvVLy1o=,tag:bmNBIvzu1badlXV7DgZ3gw==,type:str]
sops:
    age:
        - recipient: age1wucu8avdv4q5et0wrpa8pgdg92rrk6dr3j0qg02yrhkratnegpnqf8qc58
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3elpadW1XZytxNVVZS0Ux
            azNZTGVoZ09tVGhxb3p4Wk9GTUk1YlBYemxJCkdHMUNHSXNYbk8rOUFxMy9VV1Uw
            d2Z0R3IySTc2Y2ZQd3NhM0RvUkRHeU0KLS0tIFBFNXZDb0E0K2JPTzF6UWZha3My
            V2s0WkNjeldLZ0hKSHRPcGlWbUQ1OE0KpCVvJA375pgSPbdpD3gWj+BYOlJJTfTE
            QlGWGizIru9ILydHAhpxjprsVs+dCioxX/plBzlZK3PQu3K2AG0iMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-24T16:14:16Z"
    mac: ENC[AES256_GCM,data:JOxGoc4pWRKqxDcuYedxlEIqslsF6gvyZeaSdYnkIQ54yMFZ8v/Z8h7VeXvM5x3uA8kBv5pJQik3NS1dbeugh8d10moQDgGQIFDnV9rIpcDXhhNnhcmiWoTb9jyDAUGKCeSqzF+BEUobSPsMBZxZxe6OnOXYxw5gs0MkyIdGhfE=,iv:6Tl8/b0cQagH1nM6QsUnBRvzNGBzBL9LniDXM6VI3L0=,tag:vF9ViseB8DLrTvUhyzoAag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
