apiVersion: v1
kind: Secret
metadata:
    name: linkding-secret
    namespace: linkding
type: Opaque
stringData:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:ikOF2rH+25L6,iv:eKuynmhRCQ4840nUdyma8gMjuis1eI0mTyaPwGIgHjM=,tag:f7tclOyeoTzBS9kyGLfxcw==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:nRMMjt16dTHrkCTnFC+KlnxWQudRU1M3,iv:BcXsY+p4kGQKcERkZ/z6l6L40LQ+tDHzf9IL3mutKio=,tag:IRs1Sqoyy7BGzhX/WCnhYA==,type:str]
    LD_SUPERUSER_EMAIL: ENC[AES256_GCM,data:m0ZQd1L5fDR1tGdmRzT0OXpAFepTd4bI,iv:0OUim6G75OsGX5t3QHqdhgQ50MRU4EcaezWiN9/DxPY=,tag:g6cMgFZbvCIhrTlE0L9C3A==,type:str]
sops:
    age:
        - recipient: age1wucu8avdv4q5et0wrpa8pgdg92rrk6dr3j0qg02yrhkratnegpnqf8qc58
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBd1hqY2xXYTl0R3hxcDhv
            REJZZ2lDTExvN1ZaelFyTEoyaEp4cXNWbzNjCmNFMStVTmptNjRQZFh1T3FzN0pZ
            dWhTYnRlODFqNlZXWXkrMnRsQ3VqVlEKLS0tIDQ4YnRFT1JyVlNHVmxMK0pWSWFN
            UGIvMmNmb1RKOS9Yb2pFYjhiMlJWbTgK64GFJiRUIMuyZYNrys15iu/tptKSX7cY
            HuwbuD62Deo+vkmkULXOk7xvII2B+BIVXhD010odgppulvkI1V15pQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-24T15:44:20Z"
    mac: ENC[AES256_GCM,data:/O4JBV+mspy6LrebwATuR4X2/e18LKGcRNdRRJ+BvdWgwquvt90sHxcff1X21mpNA24X5AhgQV7+resdqQy+8GEJbJ21HHm0xC7Hyf58hAnihQSlJ59UEnKaTVeMlbwJYd76+Fjf8xR052yBFqjvq3+bJj8+KAOAtqVwgOkNBhk=,iv:IoYeYZLDyUXUvZ8j2nWhDvWWB1lSKpBMnMAt/A4uat8=,tag:QzQa+hcJc8yJVwk5TMpP9w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
