apiVersion: v1
kind: Secret
metadata:
    name: opsimath-secrets
    namespace: opsimath
type: Opaque
stringData:
    RAILS_MASTER_KEY: ENC[AES256_GCM,data:+PPb6ZvIUARuDYnu8jv3xE/Bf7hqozFC63XF8wgu/1Y=,iv:/aNCxZ96TGLwHyvDIcuhqeaTNfRw4imPHE5BO6Znu48=,tag:jSH3NtS9tle+KR5Zi4b23A==,type:str]
    APP_DATABASE_PASSWORD: ENC[AES256_GCM,data:Vm7PSZY9O91RN9J/TgLzJOATsHsPXm9ieri0LTmLTG7+ylBijtC0ZQ==,iv:+kutel9VGtZP2JIdPWQcGC5m533tP0c3zENd+k/Uw84=,tag:ZFMVtXyTMcA2+pH1aOiXWw==,type:str]
sops:
    age:
        - recipient: age1wucu8avdv4q5et0wrpa8pgdg92rrk6dr3j0qg02yrhkratnegpnqf8qc58
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkS1lhVy91WWhuQXRMcFFB
            ekF0ZllTWUl1T0pONXFhMHp5eEdSRlIrM0M4CjNUaDJ6Nkl4OTZHRXRodDc3Qjl5
            SUd0SkFNUXBPZVE5VmY4Unc5TXV4WXcKLS0tIGRIZE5HUXg0aGVmamxJZDAveGNt
            OUw2T0RIR090c1VyTGJWNWNTU0ozckkKR/IpMNiF1JNNzwNednQneSMEEzADRCXk
            nneaE2BE6z5omKFCN3zM6Yi2UTN2XMO0pVzSL8WUdL0xm9dNBZbxHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T19:29:12Z"
    mac: ENC[AES256_GCM,data:zlLc9+Fjet0bRpwmxX3RClww/E5x3bipX6+paTv2neZ4cQ4QrreNC7l88hTZEwbhAp8ejnbx9naf4vvCOv6hVDqlCorGTBQE9rr1/W2zSYxzU6lQ52bGKt9VcvcyllJ7QCHaaIaYb8fJRZEZItHy7e1o7g+xlWl8koPHzqoSk8o=,iv:XXyG4RNu6XymIGC99pQmhpdJoTzevXHB54lTNed0ndY=,tag:0CbhR7vJm6gCmJrjkVORhg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
