apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: epigone
  namespace: epigone
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`epigone.ecafe.org`)
      kind: Rule
      services:
        - name: homeassistant-service
          namespace: home-assistant
          port: 8123
  tls:
    secretName: epigone.ecafe.org-production
