apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 10m
  timeout: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: tailscale-operator
      version: "1.x.x"
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: tailscale
  valuesFrom:
    - kind: Secret
      name: operator-oauth
      valuesKey: client_id
      targetPath: oauth.clientId
    - kind: Secret
      name: operator-oauth
      valuesKey: client_secret
      targetPath: oauth.clientSecret
  values:
    operatorConfig:
      defaultTags:
        - "tag:k8s"
