apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:0tGSkG73DgdNLAl+CnqmBOo=,iv:TJ+mB63X8aOKIJwVn02q+GEZTjzX2Kk1i3bbMAAvm8A=,tag:F5TS6y4jLB/bByIB2ngD9Q==,type:str]
    client_secret: ENC[AES256_GCM,data:h+2nTjLZWoQ5AXOdFUNu4Aj/6vvkIO/1WelYDD3IWaooIrKwcTFgLm7/f/iyNJMUiqWFkc7XemOtIJWmNAsfjw==,iv:4nLHCeRgo7s69oKhMdROM4ZvwRLY4kbwz5kYToqv7I4=,tag:6JZfPcKaG4StJP+psmtu5g==,type:str]
sops:
    age:
        - recipient: age1wucu8avdv4q5et0wrpa8pgdg92rrk6dr3j0qg02yrhkratnegpnqf8qc58
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1a1EwekJ1dFl1OTdINXhV
            SEJMaURMakxJOU5oNS84UkliU1AxMm1ic3hBCm41RmU3NjRxZDArNUlKWU9kUmlq
            bGNxZGhyZHZUdlNrcjg0TGRIT1BMVFEKLS0tIGFmY0ZhVXYxZUVRN0RINGtSNXRQ
            REtSdXJPcktmM25EUjJCTkM0K3RHR1kKuralvPZDNQ/QHgwa1HoGJeTbwx0wsYNi
            u4Xu11kWc2Rj5Xgj9bZx28tjAV4p/1ueKgiXn0KScJIAeXxn46bqTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T16:12:21Z"
    mac: ENC[AES256_GCM,data:+SRy+2m5enUvCB9LW8seIqBfRRPFU8MFchX6Pq7QQ7zOsDSCB9dUpPJXW4dcuPvWqzcCK5o2uTLycog/GWzqmVijW5mkkywEWeqS2PIdi6V3OHJGnXXdKC42kGH0jKtq5/iLB4ZcVysy87lZt1pFrbAozFuOYUZuFMtm2WjQsH4=,iv:94gaQPAZaEruVmTdyA0nemt6ADawdz0d7X496tTek1M=,tag:asG1WoG1yyGOGmGYk7+dGw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
