apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mdns-repeater-worker
  namespace: default
spec:
  selector:
    matchLabels:
      app: mdns-repeater-worker
  template:
    metadata:
      labels:
        app: mdns-repeater-worker
    spec:
      hostNetwork: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
      initContainers:
        - name: disable-multicast-snooping
          image: alpine:3.21
          command: ["sh", "-c", "echo 0 > /sys/class/net/cni0/bridge/multicast_snooping"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: sys
              mountPath: /sys
      containers:
        - name: mdns-repeater
          image: docker.io/monstrenyatko/mdns-repeater:latest
          command: ["/bin/mdns-repeater"]
          args: ["-f", "eth0", "cni0"]
          securityContext:
            privileged: true
      volumes:
        - name: sys
          hostPath:
            path: /sys
      restartPolicy: Always
