apiVersion: v1
kind: Secret
metadata:
    name: freshrss-secret
    namespace: freshrss
type: Opaque
stringData:
    FRESHRSS_INSTALL: ENC[AES256_GCM,data:5pXP4+QZ63bD2k+3cNvmEcsID3PM0wLwcJVEezYTa1iGDyciMlG6N/VmuWICj0QlR2J8V6E+87vYNCJXcjpGVOvFXXK00NRbYU2ra3aAj6yzsPjYifNIbrMciwu6t790y3PLulQ0IijJTXT8dyY=,iv:BtmUP90cw45FlMGvkAvqfQ3yWigDykQmCfLxdmG45wY=,tag:uzUOAFsQxZ/2av1dzM4tHw==,type:str]
    FRESHRSS_USER: ENC[AES256_GCM,data:cUzqAOQ4W6COx/2phDzodpGl3Z7firYpAhk15khH/1sr/b5RY8rBV7zAjM/EG3/9rpIIOTReoVmkFc4uZ5Hbrv4wBNfODCmKkxzdwYVTLaAp0eqNIgBC+8gdaoKi9fz2Pw1nVkETxOxT3+XQh0cihO5IvKZQkFdE5PhZ,iv:aIG9U2Yk2Dx+w2LhOtHo1Vse1UWt8HEzAXLyp6Opup4=,tag:Dm73OYHzCbXMobtQVspltA==,type:str]
sops:
    age:
        - recipient: age1wucu8avdv4q5et0wrpa8pgdg92rrk6dr3j0qg02yrhkratnegpnqf8qc58
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYlpKMFpyOUc1RWd1QXQr
            MGRtbTFza1pyMGpWTGVHay90dnFhREtyZVI0CmhSZ04rVkRpbDZjMkp0b3h2MGJM
            a1RvL3JSSS9lZTRMU3k0djZHSDFpcVEKLS0tIElDU1k4WVFLRWllUFJjNDdaNW0r
            RGlkZlBlWE1xb2NZblEySFFrYmpjQUEKtK7LLeB7wKP4qt5Lj5vp3xGzygujrZsx
            xHkL6ThhhmQELiK9D6PsJ3Olhm+aPqrfzoEdXotVDZAKiq02bbnNzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-24T17:43:49Z"
    mac: ENC[AES256_GCM,data:GwiVysIBuOXINCV9hq/n6JiU6ujocPxpeaim8+FIPdA3JslytXSTSUXYyW7yiCG1qOEXHKtznu3vS3LVantpLECTsltu2/nJ81fMOiw7agILMDJsAzd/OmkxPDwgWbAUtIf81KHtnrCJou7YwJJmbIxEBhXOiUiSwiH1T8TSkEA=,iv:t1nCsp+cxY69jdUhOyY7hO/Dnk9UGdNP8Nxiiw3ZNvk=,tag:kb+uqD4R5Gztsr/BBENH1Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
