apiVersion: v1
kind: Secret
metadata:
    name: freshrss-secret
    namespace: freshrss
type: Opaque
stringData:
    FRESHRSS_INSTALL: ENC[AES256_GCM,data:b4rq55fEYeyEpIRbf24RyhVuRXDui6YGaHUXC14xjsUVXxigYQtI4G5+8lcZ68YXPzlKKS7tU2TsBrwxNaeld4OfbqJ5Obv5+uTw6iQsv5vrLiqgQbqey4VnzBjcCa/s9ZDKcMElVcx8,iv:HpiNplhouqaV12a25eOfmUKtvCf+aszgZrdCtErXRmY=,tag:kTG8L3Z5png59nRQVOJF/w==,type:str]
    FRESHRSS_USER: ENC[AES256_GCM,data:cUzqAOQ4W6COx/2phDzodpGl3Z7firYpAhk15khH/1sr/b5RY8rBV7zAjM/EG3/9rpIIOTReoVmkFc4uZ5Hbrv4wBNfODCmKkxzdwYVTLaAp0eqNIgBC+8gdaoKi9fz2Pw1nVkETxOxT3+XQh0cihO5IvKZQkFdE5PhZ,iv:aIG9U2Yk2Dx+w2LhOtHo1Vse1UWt8HEzAXLyp6Opup4=,tag:Dm73OYHzCbXMobtQVspltA==,type:str]
sops:
    age:
        - recipient: age1wucu8avdv4q5et0wrpa8pgdg92rrk6dr3j0qg02yrhkratnegpnqf8qc58
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYlpKMFpyOUc1RWd1QXQr
            MGRtbTFza1pyMGpWTGVHay90dnFhREtyZVI0CmhSZ04rVkRpbDZjMkp0b3h2MGJM
            a1RvL3JSSS9lZTRMU3k0djZHSDFpcVEKLS0tIElDU1k4WVFLRWllUFJjNDdaNW0r
            RGlkZlBlWE1xb2NZblEySFFrYmpjQUEKtK7LLeB7wKP4qt5Lj5vp3xGzygujrZsx
            xHkL6ThhhmQELiK9D6PsJ3Olhm+aPqrfzoEdXotVDZAKiq02bbnNzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-24T17:48:05Z"
    mac: ENC[AES256_GCM,data:xsoL7zpCtG7UQqbqQvwrAKEKPrGkLxRcNfmLMf2lxHse3jvuXmocBBig2dpT+2lvOtrJlJeww3RMEUprD+/fZLx2sQuT0gks8ZJBGa2d+1x2NlXPpe3mtTQYmqWHECt9Awg/Rk5ABRzFGXlcIEvQZwqbyT8PordilWUmzVd+Qd0=,iv:3ucv5HUtBpxE6AB/OikSo71AI0OyTiMnJ3jJr69YjWE=,tag:lYbp/EQCzWMf+8KjXvmZVg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
