apiVersion: v1
kind: PersistentVolume
metadata:
  name: freshrss-data-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  claimRef:
    name: freshrss-data-pvc
    namespace: freshrss
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  volumeMode: Filesystem
  nfs:
    path: /mnt/md0/k8s/freshrss-data
    server: 192.168.0.76
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-data-pvc
  namespace: freshrss
spec:
  volumeName: freshrss-data-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: freshrss-extensions-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    name: freshrss-extensions-pvc
    namespace: freshrss
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  volumeMode: Filesystem
  nfs:
    path: /mnt/md0/k8s/freshrss-extensions
    server: 192.168.0.76
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-extensions-pvc
  namespace: freshrss
spec:
  volumeName: freshrss-extensions-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
