apiVersion: v1
kind: Secret
metadata:
    name: nas-diskio-ssh-key
    namespace: monitoring
type: Opaque
stringData:
    id_ed25519: ENC[AES256_GCM,data:cFtsYfnt0iDrIKE6fPeYm1rv3mXNRIhxCOWCOBcvvnFcFj5FyGIsYM/N/opCPF/eowln4AkYNx5NyyH1DXWBAgKu0t5zDwky5/kbEGPgJNv8oW5Aq0nSC/uMlEeCk1Ir3E/VOulFvAaYdLB0HlE/6UD0hnl3bPdL+K+FDFvK1vgroepMxnq6FjXBXrwtBjpHzLye0W5iCYzbr2zxywNRAX3/rQCBCAAge4Xzq9vwwpXXjMDGODtkU1OoEBHC3+/KlxiHmO4M6Hhq74gJa3DWrhkmNQdHcvvPRvobPaa26Y3TTvw32Jn7pk1q1rIDgR2wCTHkV25kUY4fsoYsYRfY3eDQncLWC2OXrdpZccTL7JV+bO0c/oPutAqAbnBUn4/4xhnrAtpyU1B0wUXUAh5FUzfQi4wCXtrzRYglAxpO4+ye1k8FFhZ+96fDVtY2kDuhRvAtWhPFeevO93HOsxi7v9OQDo+ZKBa0m5/U3RHysoEOJbsMWkMv8g1TaUvyXqzWc4bUC3f6enpaU8X2osDefC3OzXua0OotZvlMl4wl5kpI2ofZTZ9DpifFNFqwcPO+,iv:nke39ocCmc0csZ+ORnd1hpWxLdRUWF66o/Ug+ZTZThI=,tag:HebRfaWH6fKXQWHBt1EalA==,type:str]
sops:
    age:
        - recipient: age1wucu8avdv4q5et0wrpa8pgdg92rrk6dr3j0qg02yrhkratnegpnqf8qc58
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVTZ4cU1vMEJnNzg3MC8v
            c2l1Y2piSDBMeWNISHB4VHhSZEpVUFU1RGxrCndnOXF5Z1hlcDY4ejZEbmtaOStr
            RmV5eDRtYkFoWDNJYytGNjlnTUNBbHcKLS0tIC91L1pkTlBsVFdETEY1WFZ6R2Zk
            TXhaMk9saDlSMnVlNHBndTVaQW9abFkKkYVvgJeAtqtBv/slKdwrH20YHRTvtvUs
            dfTCoK5Y+VpFoYG+/BSwtqEBdrNM6NZeIK4ZVMKP1QM4nm8TXrTdtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-23T10:54:56Z"
    mac: ENC[AES256_GCM,data:5wmPzaVG05iphGRyrO5woL61DsLs5aZFwOwwyKLQtoRayaBLchAwJwc35z7B7t4vcAB0X7co2Z2u+ugQyGwCkN68tXSFmSPkdm31g7ENIqiKHZ4QY0MPfxutSAHlq/ZJ6cZtyqQgesZO2hGaZ8MUAWdbg3Vc6esp2C+ScCQtFg0=,iv:jrddljyBzQSdMnAG98js35iSIsqU80cm3iRLcjmEcC4=,tag:l3BngpTfe2/XAI/RqhTFPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
