apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: default
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:yRXzeAIEuv8xOsXPSFneXdCdt4tkQmTRaNr6l73ByHtJxCeesqLY6Hj4hKNYJrNbqjlBlO31LMUIKMIXYkL9aX+wVMHSPiEVu/TPrlVTkSD20CLYrP8UWmmhBr1wEh5KniBlJboxgbwHADBGrvXMIKYejroD5mv01w==,iv:gAGrJ7WZHbsx9Mz1vEIbc9Sa4apT3AfvlgGARnf61OI=,tag:V2kvNuNy3w3Z24G/vKVEtA==,type:str]
sops:
    age:
        - recipient: age1wucu8avdv4q5et0wrpa8pgdg92rrk6dr3j0qg02yrhkratnegpnqf8qc58
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwY28wTm1VamtjWnBYL2tp
            N1o4NnlEQ1MzdGJ0TjlEMUhJRUo3b2NMMHdvClJlcm1zaHVjWVJJOC9lQXF2OGw5
            M1J0N0g5cTVYY2Q5eHpZNVJCRG0yMTAKLS0tIEM5bFJQNUYycm9Dc3ErMERHM3ZJ
            MktFUWttVXAxdGdYNUdHeXpPd2h5QXMKJ0AGS3eD71ahqZ5JN2ZqjTu55K4ZoP5H
            s2RL43X6bbNxWAVSMxJohj7aTdKdisqGQyJalfeTFqxSjYOubQGubA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T16:01:44Z"
    mac: ENC[AES256_GCM,data:LPXxo8JeHu9AXetuiTHK2vC4tY7UiNrah013tsT8WTJ7z82p3YJSHHrwYkIkOc85MNjRtvK/RGrohkNwLRLKkcjFnbFTAC5Q52ygxbqsyjIAyvdhmEqaMmXbZy5mHoR181225RUXz+KuTE6bUMIryaIInQr2RJot2J/ASsVnNXw=,iv:8TcGv6Psgka5MtEKySJwfk/Mmx5SQPbwDhBxYTRNxQ4=,tag:cPFdUEQjI+ikzRKO/llm/Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
