apiVersion: v1
kind: PersistentVolume
metadata:
  name: syncthing-config-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    name: syncthing-config-pvc
    namespace: default
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  volumeMode: Filesystem
  nfs:
    path: /mnt/md0/sync/config
    server: 192.168.0.76
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-config-pvc
  namespace: default
spec:
  volumeName: syncthing-config-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: syncthing-data-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    name: syncthing-data-pvc
    namespace: default
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  volumeMode: Filesystem
  nfs:
    path: /mnt/md0/sync/data
    server: 192.168.0.76
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-data-pvc
  namespace: default
spec:
  volumeName: syncthing-data-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
