apiVersion: apps/v1
kind: Deployment
metadata:
  name: modpoll
  labels:
    app: modpoll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modpoll
  template:
    metadata:
      labels:
        app: modpoll
    spec:
      terminationGracePeriodSeconds: 10
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
      containers:
        - name: modpoll
          image: topmaker/modpoll:1.6.0
          command: ["modpoll", "--tcp=192.168.0.188", "-f", "/etc/modpoll.cfg", "--mqtt-host=mosquitto", "--mqtt-publish-topic-pattern", "solar/{{device_name}}", "--mqtt-version", "5.0"]
          volumeMounts:
          - name: modpoll-config-volume
            mountPath: /etc/modpoll.cfg
            subPath: modpoll.cfg
      volumes:
        - name: modpoll-config-volume
          configMap:
            name: modpoll-config
